### ISSUE TITLE
Bin dabei mit solarlog/smappee/luxtronik1/comfoair

### ISSUE THREAD

**Issue by forelleblau** [iobroker-community-adapters/info#11]
Würde mich über die entsprechende Einladung freuen.

**Comment by Jey-Cee** [comment]
Bist bei github und npmjs eingeladen.

**Comment by forelleblau** [comment]
Comfoair:
- [1. Go to your GitHub repo that you want to move ] 
- [ 2. Change URLs in io-package.json, package.json and README.md form your GitHub repo to Org repo  ]
- [ 3. Settings -> Danger Zone -> Transfer Ownership] 
- [4. Click on 'Transfer' ] 
- [5. Type 'iobroker-community-adapters' as New owner ] 
- [6. Add the oranization as an owner of your npm packages (npm access grant read-write iobroker-community-adapters:developers iobroker.<adaptername>) ] 
- [7. Change the url of your repo via pull req at https://github.com/ioBroker/ioBroker.repositories
 ] 
- [ 8. Thats it ]

luxtronik1
- [1. Go to your GitHub repo that you want to move ] 
- [ 2. Change URLs in io-package.json, package.json and README.md form your GitHub repo to Org repo  ]
- [ 3. Settings -> Danger Zone -> Transfer Ownership] 
- [4. Click on 'Transfer' ] 
- [5. Type 'iobroker-community-adapters' as New owner ] 
- [6. Add the oranization as an owner of your npm packages (npm access grant read-write iobroker-community-adapters:developers iobroker.<adaptername>) ] 
- [7. Change the url of your repo via pull req at https://github.com/ioBroker/ioBroker.repositories
 ] 
- [ 8. Thats it ]

smappee
- [1. Go to your GitHub repo that you want to move ] 
- [ 2. Change URLs in io-package.json, package.json and README.md form your GitHub repo to Org repo  ]
- [ 3. Settings -> Danger Zone -> Transfer Ownership] 
- [4. Click on 'Transfer' ] 
- [5. Type 'iobroker-community-adapters' as New owner ] 
- [6. Add the oranization as an owner of your npm packages (npm access grant read-write iobroker-community-adapters:developers iobroker.<adaptername>) ] 
- [7. Change the url of your repo via pull req at https://github.com/ioBroker/ioBroker.repositories
 ] 
- [ 8. Thats it ]

solarlog
- [1. Go to your GitHub repo that you want to move ] 
- [ 2. Change URLs in io-package.json, package.json and README.md form your GitHub repo to Org repo  ]
- [ 3. Settings -> Danger Zone -> Transfer Ownership] 
- [4. Click on 'Transfer' ] 
- [5. Type 'iobroker-community-adapters' as New owner ] 
- [6. Add the oranization as an owner of your npm packages (npm access grant read-write iobroker-community-adapters:developers iobroker.<adaptername>) ] 
- [7. Change the url of your repo via pull req at https://github.com/ioBroker/ioBroker.repositories
 ] 
- [ 8. Thats it ]

**Comment by jogibear9988** [comment]
probiers mal auf der npm webseite die rechte hinzuzufügen. mit den commands klappts als (oft) nicht

**Comment by forelleblau** [comment]
Danke für den Tipp, kann ich als MEMBER eben auch nicht. Oder reicht es, das Team als Maintainer für die package einzuladen?

**Comment by jogibear9988** [comment]
nun bist admin

**Comment by jogibear9988** [comment]
@forelleblau bist auch bei telegram?

**Comment by forelleblau** [comment]
Nein, bin ich nicht. Sollte ich das? Dafür ist iobroker.comfoair jetzt bei den community-adapters auf npm. Danke für den Admin.

**Comment by jogibear9988** [comment]
da gibts halt einen chat, in dem die ganzen community Entwickler sind. Wenn fragen hast bekommst da am schnellsten eine antwort

**Comment by jogibear9988** [comment]
der link dazu im readme: https://github.com/iobroker-community-adapters/info
