### ISSUE TITLE
add ioBroker.fontui

### ISSUE THREAD

**Issue by runsnbunsn** [iobroker-community-adapters/info#17]
hi!

plz add me so
https://github.com/runsnbunsn/ioBroker.fontui

can get to the repo

**Comment by Jey-Cee** [comment]
Do you plan to transfer fontui to community adapters? If not it is not necessary that you are a member of the organization. But you're welcome in both cases.

**Comment by runsnbunsn** [comment]
No I was just planning to have it added to the repo with the next version...

**Comment by Apollon77** [comment]
Then please check the details here https://github.com/ioBroker/ioBroker.repositories#iobrokerrepositories
