### ISSUE TITLE
Migration of ioBroker.squeezebox and ioBroker.kecontact

### ISSUE THREAD

**Issue by UncleSamSwiss** [iobroker-community-adapters/info#18]
I would like to move the squeezebox and kecontact adapters to the community adapter org for the following reasons:
- squeezebox: I haven't used the adapter a lot myself (even though I still own and use two working Squezebox devices) and others might like to contribute more than me
- keconact: I wrote this adapter when I was idle even thought I don't own a KEBA Wallbox, so further development should happen by people that actually own the hardware

Can you please add me to your organisation so I can move those two adapters (all my other adapters will remain under my user).

**Comment by Jey-Cee** [comment]
You are invited

**Comment by UncleSamSwiss** [comment]
ioBroker.squeezebox has been migrated to https://github.com/iobroker-community-adapters/ioBroker.squeezebox

**Comment by UncleSamSwiss** [comment]
ioBroker.kecontact has been migrated to https://github.com/iobroker-community-adapters/ioBroker.kecontact
