### ISSUE TITLE
add me please

### ISSUE THREAD

**Issue by EdgarM73** [iobroker-community-adapters/info#19]
Hi there,

could you please add me as well, so i can move my adapter to io community?

edgarm73 in nmpjs.com

regards
E

**Comment by Jey-Cee** [comment]
You are invited

**Comment by EdgarM73** [comment]
Still getting error message when transfering to community:

You don’t have the permission to create public repositories on iobroker-community-adapters 

What did i miss?

**Comment by Jey-Cee** [comment]
You did not accept the invite
