### ISSUE TITLE
Create a gulp task to move adapters to iobroker-community-adapters

### ISSUE THREAD

**Issue by ldittmar81** [iobroker-community-adapters/info#2]
- [ ] look for links and adapt if necessary (package.json, io-package.json, README.md

- [ ] add task to create-adapter (gulpfile.js)

- [ ] automatic create pr to iobroker.repositories (latest/stable)

- [ ] create a checklist on the readme, for repo migration

**Comment by jogibear9988** [comment]
can or will you do it?

**Comment by jogibear9988** [comment]
maybe we should include the task that also a pull req to iobroker.repositories should be created

**Comment by jogibear9988** [comment]
or at first create a checklist on the readme, for repo migration

**Comment by ldittmar81** [comment]
> can or will you do it?

Ähh.... time is my enemy :rofl:

**Comment by mcm1957** [comment]
I do not see any need for it.
Haver moved several adapters during the last months. Not so much work.
AND real work is doing adapters required like testing, linter correctsion etc. which can not be done outomatically.

I will move any adapter if requested in future untill I state some different.
So lets close here.
