### ISSUE TITLE
I would like to get a member of iobroker-community-adapters

### ISSUE THREAD

**Issue by hacki11** [iobroker-community-adapters/info#20]
I would like help to maintain and add features to adapters owned by the community.
First i will focus on to the fronius adapter but will not hesitate to help here and there.

my references:
https://github.com/hacki11/ioBroker.valloxmv
https://github.com/hacki11/ioBroker.bsblan

**Comment by Jey-Cee** [comment]
You are invited on Github and npm

**Comment by hacki11** [comment]
Thanks!
