### ISSUE TITLE
Problems with npm grant acccess for ring adapter 

### ISSUE THREAD

**Issue by schmupu** [iobroker-community-adapters/info#22]
I get following error if I try to give the community access to npm.

```
npm access grant read-write iobroker-community-adapters:developers iobroker.ring

npm ERR! code E403
npm ERR! 403 403 Forbidden - PUT https://registry.npmjs.org/-/team/iobroker-community-adapters/developers/package - Forbidden
npm ERR! 403 In most cases, you or one of your dependencies are requesting
npm ERR! 403 a package version that is forbidden by your security policy.

```

**Comment by Jey-Cee** [comment]
Go to https://www.npmjs.com/settings/iobroker-community-adapters/teams/team/developers/access, enter the name of the package and hit Add Existing Package

**Comment by schmupu** [comment]
I do not have the permission to add a package with https://www.npmjs.com/settings/iobroker-community-adapters/teams/team/developers/access , I am sorry

**Comment by Jey-Cee** [comment]
Now you have
