### ISSUE TITLE
Please add me as a member

### ISSUE THREAD

**Issue by ruhr70** [iobroker-community-adapters/info#28]
**npm:** 
npm@herwig.de / ruhr70
Enter your email or name on npmjs.com **Important and not optional**

**chat:** 
ruhr70
Give us your Telegram name, alternative join the [official Discord](https://discord.gg/HwUCwsH) server and contact the Administrator to get access to the channel. 
This chat is only for administrative topics.

**Comment by Apollon77** [comment]
lets use the first PR #27  :-))

It is a "manual human made process" :-) so nothing automatic
