### ISSUE TITLE
Please add me as a member

### ISSUE THREAD

**Issue by Patrick-Walther** [iobroker-community-adapters/info#29]
**npm:** 
Enter your email or name on npmjs.com **Important and not optional**

patrickwaltherh

**chat:** 
Give us your Telegram name, alternative join the [official Discord](https://discord.gg/HwUCwsH) server and contact the Administrator to get access to the channel. 
This chat is only for administrative topics.
Patrick in der Iobroker Entwicklungsgruppe
Discord PatrickWalther#6838

**Comment by MeisterTR** [comment]
(npm name: patrickwaltherh)   :)

**Comment by Apollon77** [comment]
Ok, GitHub already done
