### ISSUE TITLE
Please add me as a member

### ISSUE THREAD

**Issue by ciddi89** [iobroker-community-adapters/info#30]
**npm:** 
ciddi89

**chat:** 
Telegram: ciddi89
Discord: ciddi89#9768

**Comment by Apollon77** [comment]
Hi and welcome, can you please give some words about your background, which adapter you maintain and why you want to be part of the Community-adapter-group?

**Comment by ciddi89** [comment]
Hello, yes sure!

I'm using ioBroker over three years now. And since few weeks I'm working on an watchdog adapter. This adapter looks for devices (Zigbee, Ble ect) and will create a list where are the devices are listet, how the signal strength is, if possible how much battery it has and if it's online or offline. When offline you can get a message. 

For me it's my first adapter and I got the tip to publish it in the community. So others can help and maybe I can help in the future on others adapter. And I have some ideas for new adapters too.

**Comment by Apollon77** [comment]
Hi, sorry, wanted to give you acces today .. why closed?

**Comment by ciddi89** [comment]
Good Evening, sry I wasn't sure if it was to early to ask for access because my adapter isn't finished now. But it's up to you. When it's okay, I will gladly come in.

**Comment by Apollon77** [comment]
@ciddi89 npm invite sent

**Comment by Apollon77** [comment]
GitHub Invite sent too

**Comment by Apollon77** [comment]
PS: Please try to add your repo to community npm ... if not working please write again as I might need to increase rights temporariely

**Comment by ciddi89** [comment]
@Apollon77 ok thanks. Adding the repo to community npm worked. I hope I'll have more time next week to work on the adapter to get it finished as fast as I can. :-)

**Comment by Apollon77** [comment]
@ciddi89 did you added the @iobroker-community-adapters/iobroker.device-watcher package on npm? This is not how the package should be names and will not work!!

Needs to be just iobroker.device-watcher with NO scope!

**Comment by Apollon77** [comment]
I have removed the package again

**Comment by Apollon77** [comment]
hmm ... I can't remove it

**Comment by ciddi89** [comment]
@Apollon77 ok thanks for the advice. I deleted it and will upload it again in the right way when it's finished.
