### ISSUE TITLE
Readme.md - duplicated adapterlist

### ISSUE THREAD

**Issue by mcm1957** [iobroker-community-adapters/info#32]
Adapters are listed twice in section maintainers.

If this is a simple edir / remove text task feell free to assign issue to me. But it looks like this list is autogenerated in some way.

**Comment by Apollon77** [comment]
DO you have a screenshot please?

**Comment by mcm1957** [comment]
Ill add one as soon as I am at my computer.
I noticed the issue at my mobile.

**Comment by mcm1957** [comment]
![Adapterlist](https://user-images.githubusercontent.com/28575778/185572108-cef20fbe-a18f-46da-9114-1e468726e050.png)

Sorry for the late answer - I'm on holiday currently

**Comment by Apollon77** [comment]
Yes, needs to be fixed https://github.com/iobroker-community-adapters/info#maintainers there ...

**Comment by mcm1957** [comment]
Note: This issue occured if data from github returned more than one page.
Should be fixed with https://github.com/iobroker-community-adapters/info/pull/33

**Comment by Apollon77** [comment]
Thank you ... ( but alexa2 is not a community adapter :-)) )

**Comment by mcm1957** [comment]
Mhmmm
https://github.com/iobroker-community-adapters/iobroker.alexa2

Someone cloned Alexa 1 into iobroker.community-adapters. So the rules for npm start match this repo. This was the case even before my change. So either the npm start scrit need an additonal filter or the fork has to be removed from iobroker.community-adapters ...

**Comment by Apollon77** [comment]
ALexa2 gehört da nicht hin ... wird gekillt

**Comment by Apollon77** [comment]
If community is a fork or a real repo depends on things. normallyboth are ok. In this case someone forked alexa2 with no reason ... I deleted that now

**Comment by mcm1957** [comment]
PR updated, Alexa2 should be removed now (not quite sure as I sometimes wonder what and why github is doing things itself :-) )

**Comment by mcm1957** [comment]
Just for Info and to avoid confusion:

I've updated README.md to remove duplicates and add several adapters added to community. But I did not commit/merge the modified script as you mayby know better how to fix the duplicates in a clean way. So I keep this issue open.

**Comment by klein0r** [comment]
Just merge it - it's an info repository 😄
