### ISSUE TITLE
Please add me as a member

### ISSUE THREAD

**Issue by xXBJXx** [iobroker-community-adapters/info#35]
**npm:**
Name: issi
E-mail:  issi.dev.iobroker@gmail.com

**GitHub:**
Name: xXBJXx
E-mail:  issi.dev.iobroker@gmail.com

**chat:** 
Telegram : @Issi_i 
Discord: Issi#2100

**adapter:**
I would then take over the [tankerkoenig](https://github.com/iobroker-community-adapters/ioBroker.tankerkoenig) adapter

**Comment by Apollon77** [comment]
Invitations.sent. Please confirm

**Comment by xXBJXx** [comment]
Thank you have accepted both
