### ISSUE TITLE
Please add me as a member

### ISSUE THREAD

**Issue by dkleber89** [iobroker-community-adapters/info#39]
**npm:** 
E-Mail: dkleber89@gmail.com
Username: dkleber89

**chat:** 
Transfer [ioBroker.beckhoff](https://github.com/dkleber89/ioBroker.beckhoff) Adapter to community

**Comment by Apollon77** [comment]
YOu should have got invites

**Comment by dkleber89** [comment]
Thanks

**Comment by dkleber89** [comment]
Too fast ... @Apollon77 -> Can u add me to the developers team on npm to grant access to package ... Thanks

**Comment by Apollon77** [comment]
I did that ... you should also have got an npm invite email ... or not?

**Comment by dkleber89** [comment]
Hmm ... i see ... Is there some extra step neccessary to add a package to the organisation? Because i think i have not the permissions. On CLI i become a 403 Forbidden and on UI a not found a option to add a package

**Comment by mcm1957** [comment]
When migrating envertech-pv apollon77 added the npm package to the organisation or changed the owner. Dont know the derail.

Further Updates are done using the npm token stored at organisation

**Comment by Apollon77** [comment]
Try again please ... I temporariely increased your right ... should allow now

**Comment by Apollon77** [comment]
Please tell when done

**Comment by dkleber89** [comment]
Done

**Comment by Apollon77** [comment]
permissions lowered again (because only affects adding packages)
