### ISSUE TITLE
Please add me as a member

### ISSUE THREAD

**Issue by zapccu** [iobroker-community-adapters/info#40]
**npm:** 
d.braner@gmx.net

**chat:** 
Discord:  dimonet#6354

I recently developed a new ioBroker adapter for the "SMA EV Charger" wallbox.

https://github.com/zapccu/ioBroker.sma-ev-charger

I'm pretty new to ioBroker development. This is my first ioBroker adapter. In the last 6 years I developed modules for FHEM smarthome platform.

I like to add my adapter to the community, but need some support on how to do this.

**Comment by mcm1957** [comment]
Hi Zapccu,

Thanks for you effort to develop an adapter for ioBroker.

First of all - I do NOT decide who and when will be added to the iobroker-community-adapters organisation. You will have to wait for an response from @Apollon77.

BUT I'm currently not sure, what you are really looking for. I had a look at you adapter and it seesm to be pretty ready to work (with one major remark I will add later. But the adapter does is not yet pubished at the ioBroker repositories and as far as I saw during a fast check no releases exist and it is not published at npm.

So the major question is:
-) do you need halb to finalize this adapter (publish a release and add it to ioBroker repositories)
-) du you transfer ownership of this adapter to the community as you cannot maintain / develop it any more 

Do not need to be member of iobroker-sommunity-adapters to have an adapter published.

Support to finalize the adapter and get is added to repositories will be provided best at telegram support channels:
adapter developer starters: https://t.me/+gsX-e8k4mLtmZjZk 
adapter developers experienced: https://t.me/ioBroker_development
both groups are shadowed at discord too: https://discord.gg/2tp43z8p

Please let us know what's you goal is and how we can help.

McM1957

P.S. According to your adapter: You are mixing await and .then usage within one function call. As long as this is not prohibited (as far as I know) it's discouraged and could be a remark at review before adding the adapter to latest repository. But here is not the place to discusse this - should be done at telegram / discord.

**Comment by mcm1957** [comment]
@zapccu 
Thankls for clearification. I will close here - feel free to open a new request wehnever you want to maintain an existing community adapter or moveyour adapter to the community organisation.

Refering to your problems releasing the adapter:

I suggest to join 
adapter developer starters: https://t.me/+gsX-e8k4mLtmZjZk
adapter developers experienced: https://t.me/ioBroker_development
both groups are shadowed at discord too: https://discord.gg/2tp43z8p

I'm only using telegram - so I cannot support at discord. You will find many experieced users to support you there.
Personally this week is a little bit difficult as I will be near offline until next friday for personal reasons.

I checked your adapter again. I'm not quite sure how you created the adapter. In general the following actions are used to create an adapter and releases:

-) use adapter-creator to create a new adapter
   Details and usage see: https://github.com/ioBroker/create-adapter
   adapter creator creates template files and sets up most utilities.
  It looks like this has been done so far

-) creating a release
   This should be done using alcazones release script.
   Details and usage see: https://github.com/AlCalzone/release-script
   Please read readme carefully and do not forget to add required plugins and setup .releaseconfig file.
   It looks like relase script has been set up

   To create a new release now a 'npm run release' should be sufficient.

-) Deploy release to npm
    whenever a new release is tagged at github the github action test-and-release is triggered. If all tests pass, the new release is 
    deployedd at github. Please ensure that the github toke is set as described inside test-and-.release.yml

So far a new release should be created and released at npm. If you encounter any errors until now, please ask (best at telegrem). We will support for sure.

At this point it is useful to  add a topic at iobroker forum (forum.iobroker.net) subfiolder testing and ask others to check / test your adapter. Please note that write access to test area at forum needs to be requested. Simply contact i.e. homoran.

Whenever you feel that your adapter is ready to get release to repositories, request an addition to lates repository. The readme https://github.com/ioBroker/ioBroker.repositories#iobrokerrepositories describes the requirements. But note, that adding might be easier using the iobroker develeoper portal (www.iobroker.dev). Select you adapter there and go to manage releases. But before you should run the adapter checker and fix errors reported.

I think this guide is a little bit long until now. So I suggest you create a release first (0.0.1, 0.0.x ...) including deploy to npm and ask for next steps as soon as this is working.

But please try to use telegram (or discord) as issues as this repository are read by ruther few people.

Thanks for your work to support ioBroker.

Mcm1957 (Matrtin)
