### ISSUE TITLE
NPM packages initially created at community orga have incorrect ownerships

### ISSUE THREAD

**Issue by mcm1957** [iobroker-community-adapters/info#41]
Adapters created directly at uibroker-cummunity-adapters orga seem to have incomplete ownership at npm:

```
E:\>npm owner ls iobroker.pid
apollon77 <github@fischer-ka.de>

E:\>
```
```
E:\>npm owner ls iobroker.nsclient
apollon77 <github@fischer-ka.de>

E:\>
```

- apollon77 please fix and / or
- let me know what the correct ownership settings would be. I could tra to add a script / task which cleans up during deploy (i.e. by adding a ```npm add user ...``` command at deploy state (- must be tested id this works)

This seesm to be a general problem with adapters created originalle insiode community area. The npm package is created by test-and-release with toke  appollon77 from github - as far as I can see. And other users / group users are not added as I can see. This should be investigated a little bit more if time is available.

**Comment by Apollon77** [comment]
I think also that one was a "moved" one. I can add proper rights when back from vacation. Which else are affected beside fronius?

**Comment by mcm1957** [comment]
Please lets discuss AFTER holidays

**Comment by mcm1957** [comment]
As discussed with @Apollon77 this is a one time issue and occures ONLY if the adapter is created directly at communities area.
The npm access rights can be corrected manually. No action reuired.

Let's close here.
