### ISSUE TITLE
Please add me as a member - nkleber78 / ioBroker.fronius

### ISSUE THREAD

**Issue by nkleber78** [iobroker-community-adapters/info#42]
**npm:** 
nkleber78

**chat:** 
Telegram: nkleber

Purpose: Maintaining https://github.com/iobroker-community-adapters/ioBroker.fronius adapter

**Comment by mcm1957** [comment]
@Apollon77 
At least selective access to ioBroker.fronius is ok from my side. nkleber did the maintainence of the old adapter and has proivided 2.0.x in meantime. See https://forum.iobroker.net/topic/65948/test-adapter-fronius-2-0-x (Thread opened by my, but content to adapter provided by nkleber)

**Comment by Apollon77** [comment]
ack

**Comment by mcm1957** [comment]
@nkleber78 
I've enabled write access to the repo ioBroker.fronius. You should be able to work directly in this repository and perform almost all operations except admin tasks like adding new users or deleting the rpository. If any desired operation is not possible, please let me know, I'll check.

Please check und let me / us know if its ok.

In addition please contact me (i.e. telegram mcm1957) before doing you first release operation. I would like to explain the usage of alcazones releasescript if required.

Welcome and THANK YOU for spending time and know how to support this adapter.

**Comment by mcm1957** [comment]
I'll close this issue for now.
Please open a new one if you want to contribute to other adapters at any time.

mcm1957
