### ISSUE TITLE
Please add me as a member - lucky-esa / ioBroker.worx

### ISSUE THREAD

**Issue by Lucky-ESA** [iobroker-community-adapters/info#43]
**npm:** 
lucky-esa
github@luckyskills.de

**chat:** 
Discord: Lucky-ESA#1817

**Reason:**
Maintaining https://github.com/iobroker-community-adapters/ioBroker.worx

**Comment by mcm1957** [comment]
@Apollon77
At least selective access to ioBroker.worx is ok from my side. Lucky-ESA did the maintainence of the old adapter and has proivided updates in meantime. See [https://forum.iobroker.net/topic/65948/test-adapter-fronius-2-0-x (Thread opened by my, but content to adapter provided by nkleber)](https://github.com/iobroker-community-adapters/ioBroker.worx/pull/700). Latest release 130 User, no issues.

If Ok, I can grant write access to worx repo.

**Comment by mcm1957** [comment]
![image](https://github.com/iobroker-community-adapters/info/assets/28575778/a5072be6-7e49-489d-9fae-143b9ac16900)

I've enabled write access to the repo ioBroker.worx. You should be able to work directly in this repository and perform almost all operations except admin tasks like adding new users or deleting the repository. If any desired operation is not possible, please let me know, I'll check.

Please check und let me / us know if its ok.

In addition please contact me (i.e. telegram mcm1957) before doing you first release operation. I would like to explain the usage of alcazones releasescript if required.

Welcome and THANK YOU for spending time and know how to support this adapter.

**Comment by Lucky-ESA** [comment]
@mcm1957 
I have full access. Great...Thanks a lot

Gruß//Bodo

**Comment by mcm1957** [comment]
@Lucky-ESA
@Apollon77 

Thanks for cleaning up workx adapter, especially cleaning up incomplete io.package news after last release by ta2k. ([5ce1f917f32b22e9316da6de3fdca4835b9b7524](https://github.com/iobroker-community-adapters/ioBroker.worx/commit/5ce1f917f32b22e9316da6de3fdca4835b9b7524))
