### ISSUE TITLE
Please add me as a member

### ISSUE THREAD

**Issue by Pmant** [iobroker-community-adapters/info#45]
**npm:** 
[pmant](https://www.npmjs.com/~pmant)

**chat:** 
discord: pmant

**Comment by Apollon77** [comment]
npm invitation sent

**Comment by Pmant** [comment]
It seems I don't have the permission to add packages to the npm org.

**Comment by Apollon77** [comment]
solved or do you need higher permissions?

**Comment by Apollon77** [comment]
Retry please and tell when done. Made you to npm admin now

**Comment by Pmant** [comment]
That worked, done.

**Comment by Apollon77** [comment]
thank yiu" rights adjusted
