### ISSUE TITLE
Please add me as a member

### ISSUE THREAD

**Issue by ticaki** [iobroker-community-adapters/info#46]
**npm:** 
ticaki

**chat:** 
Tim Kiemen 

ioBroker.plex

**Comment by mcm1957** [comment]
@ticaki

You should have full write access to repo plex now.
Only some admin restricted things like deleting the repository or ading access right will be blocked.

Please check und respond if any action you wish to do does not work.

I'll close here for now.
Please feel free to open a new request if you think  access to other adapters or the complete group of adapters would be appropiate.

THANKS for you contribitions!
