### ISSUE TITLE
Please add me as a member 

### ISSUE THREAD

**Issue by aruttkamp** [iobroker-community-adapters/info#51]
**npm:** 
aruttkamp

**chat:** 
@aruttkamp
Give us your Telegram name, alternative join the [official Discord](https://discord.gg/HwUCwsH) server and contact the Administrator to get access to the channel. 
This chat is only for administrative topics.

channels joined ;-) 

Ich möchte bitte den spotify-premium adapter warten. 
Dazu fehlen mir die passenden Berechtigungen ;-) 

Andreas

**Comment by jogibear9988** [comment]
added yoou
