### ISSUE TITLE
Migrate soef adapters to community

### ISSUE THREAD

**Issue by jogibear9988** [iobroker-community-adapters/info#7]
Migrate the following Adapters to Community Repos:
(all checked in prepare is already done for this adapters)

- [ ] ioBroker.hid https://github.com/soef/ioBroker.hid
- [x] ioBroker.tr-064 https://github.com/soef/ioBroker.tr-064
- [ ] iobroker.js2fs https://github.com/soef/iobroker.js2fs
- [ ] ioBroker.wifilight https://github.com/soef/ioBroker.wifilight
- [ ] ioBroker.yamaha https://github.com/soef/ioBroker.yamaha
- [ ] ioBroker.wm-bus https://github.com/soef/ioBroker.wm-bus
- [ ] ioBroker.samsung https://github.com/soef/ioBroker.samsung
- [ ] ioBroker.miele https://github.com/soef/ioBroker.miele
- [ ] ioBroker.lightify https://github.com/soef/ioBroker.lightify
- [ ] ioBroker.find-my-iphone https://github.com/soef/ioBroker.find-my-iphone

Following are not yet in Repo
(nothing of the steps has been done!)
- [x] ioBroker.firetv https://github.com/soef/ioBroker.firetv (not in repo!!)
- [ ] ioBroker.mysensors-2 https://github.com/soef/ioBroker.mysensors-2 (not in repo!!)
- [ ] ioBroker.koubachi https://github.com/soef/ioBroker.koubachi (not in repo!!)
- [x] ioBroker.cec https://github.com/soef/ioBroker.cec (not in repo!!)

Todo's

Prepare:
- [x] Fork the Repo (Ingo)
- [x] Rename Repo to xxxx-community (Ingo)
- [x] merge Adapter-Core pull req. from Apollon77 (Ingo)
- [x] enable base testing
- [x] move issues to new repo
- [x] create issue in old repo wich links to the new 
- [x] move pull req's to new repo
- [x] add a link in readme.md to original repo and a thank you

Next Steps
- [ ] update files in repo to point to new repo (readme, io-package, package)
- [ ] Implement Compact Mode
- [ ] create admin3 config
- [ ] create new npm packages, update npm links
- [ ] update urls in ioBroker.repositorys

**Comment by jogibear9988** [comment]
don't think this issue is relevant any more...

**Comment by mcm1957** [comment]
yep
